// <auto-generated />
using Footprint.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Footprint.Infrastructure.Migrations
{
    [DbContext(typeof(FootprintDbContext))]
    [Migration("20190822162530_initial-footprint")]
    partial class initialfootprint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Footprint.Infrastructure.Model.DailyFootprint", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Footprints");
                });
#pragma warning restore 612, 618
        }
    }
}
