// <auto-generated />
using System;
using Itinere.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Itinere.Infrastructure.Migrations
{
    [DbContext(typeof(ItinereDbContext))]
    [Migration("20190903233415_coffee-time")]
    partial class coffeetime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Itinere.Infrastructure.Model.CoffeeTime", b =>
                {
                    b.Property<string>("_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FootprintId");

                    b.Property<DateTime>("When");

                    b.Property<string>("With");

                    b.HasKey("_id");

                    b.HasIndex("FootprintId");

                    b.ToTable("CoffeeTime");
                });

            modelBuilder.Entity("Itinere.Infrastructure.Model.Footprint", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Footprints");
                });

            modelBuilder.Entity("Itinere.Infrastructure.Model.CoffeeTime", b =>
                {
                    b.HasOne("Itinere.Infrastructure.Model.Footprint", "Footprint")
                        .WithMany("CoffeeTimes")
                        .HasForeignKey("FootprintId");
                });

            modelBuilder.Entity("Itinere.Infrastructure.Model.Footprint", b =>
                {
                    b.OwnsOne("Itinere.Infrastructure.Model.Dung", "MorningDung", b1 =>
                        {
                            b1.Property<string>("FootprintId");

                            b1.Property<string>("Description");

                            b1.Property<int>("Solidity");

                            b1.ToTable("Footprints");

                            b1.HasOne("Itinere.Infrastructure.Model.Footprint")
                                .WithOne("MorningDung")
                                .HasForeignKey("Itinere.Infrastructure.Model.Dung", "FootprintId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
